facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: 3fbc0a2841bc92085523
    clientSecret: 23a6b873d7b25e3ed8fab52954978cc4b52cfec6
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    useCurrentUri: false
    preEstablishedRedirectUri: http://localhost:8080/login/github
  resource:
    userInfoUri: https://api.github.com/user

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
      registered-redirect-uri:
        - http://localhost:9999/client/login
        - http://sso-auth-client:9999/client/login

spring:
  datasource:
#    url: jdbc:hsqldb://localhost:3306/auth
    username: sa
    password: sa

---
spring:
  profiles: test

github:
  client:
    clientId: 3fbc0a2841bc92085523
    clientSecret: 23a6b873d7b25e3ed8fab52954978cc4b52cfec6
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

---
spring:
  profiles: pro

github:
  client:
    clientId: 3fbc0a2841bc92085523
    clientSecret: 23a6b873d7b25e3ed8fab52954978cc4b52cfec6
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    useCurrentUri: false
    preEstablishedRedirectUri: http://localhost:8080/login/github
  resource:
    userInfoUri: https://api.github.com/user
